# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arm.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'arm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tarm.proto\x12\x07openarm\"B\n\x0e\x43\x61rtesianDelta\x12\n\n\x02\x64x\x18\x01 \x01(\x02\x12\n\n\x02\x64y\x18\x02 \x01(\x02\x12\n\n\x02\x64z\x18\x03 \x01(\x02\x12\x0c\n\x04\x64r6d\x18\x04 \x03(\x02\"4\n\x12\x41rmCommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x14\n\x12GetArmStateRequest\"Q\n\x08\x41rmState\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0b\n\x03r6d\x18\x04 \x03(\x02\x12\x17\n\x0fjoint_positions\x18\x05 \x03(\x02\"\'\n\x0cResetRequest\x12\x17\n\x0fjoint_positions\x18\x01 \x03(\x02\"\x10\n\x0e\x41rmPingRequest\"9\n\x0f\x41rmPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x02 \x01(\x01\x32\x8f\x02\n\nArmService\x12J\n\x12SendCartesianDelta\x12\x17.openarm.CartesianDelta\x1a\x1b.openarm.ArmCommandResponse\x12=\n\x0bGetArmState\x12\x1b.openarm.GetArmStateRequest\x1a\x11.openarm.ArmState\x12;\n\x05Reset\x12\x15.openarm.ResetRequest\x1a\x1b.openarm.ArmCommandResponse\x12\x39\n\x04Ping\x12\x17.openarm.ArmPingRequest\x1a\x18.openarm.ArmPingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTESIANDELTA']._serialized_start=22
  _globals['_CARTESIANDELTA']._serialized_end=88
  _globals['_ARMCOMMANDRESPONSE']._serialized_start=90
  _globals['_ARMCOMMANDRESPONSE']._serialized_end=142
  _globals['_GETARMSTATEREQUEST']._serialized_start=144
  _globals['_GETARMSTATEREQUEST']._serialized_end=164
  _globals['_ARMSTATE']._serialized_start=166
  _globals['_ARMSTATE']._serialized_end=247
  _globals['_RESETREQUEST']._serialized_start=249
  _globals['_RESETREQUEST']._serialized_end=288
  _globals['_ARMPINGREQUEST']._serialized_start=290
  _globals['_ARMPINGREQUEST']._serialized_end=306
  _globals['_ARMPINGRESPONSE']._serialized_start=308
  _globals['_ARMPINGRESPONSE']._serialized_end=365
  _globals['_ARMSERVICE']._serialized_start=368
  _globals['_ARMSERVICE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
