# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import arm_pb2 as arm__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCartesianDelta = channel.unary_unary(
                '/openarm.ArmService/SendCartesianDelta',
                request_serializer=arm__pb2.CartesianDelta.SerializeToString,
                response_deserializer=arm__pb2.ArmCommandResponse.FromString,
                _registered_method=True)
        self.GetArmState = channel.unary_unary(
                '/openarm.ArmService/GetArmState',
                request_serializer=arm__pb2.GetArmStateRequest.SerializeToString,
                response_deserializer=arm__pb2.ArmState.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/openarm.ArmService/Reset',
                request_serializer=arm__pb2.ResetRequest.SerializeToString,
                response_deserializer=arm__pb2.ArmCommandResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/openarm.ArmService/Ping',
                request_serializer=arm__pb2.ArmPingRequest.SerializeToString,
                response_deserializer=arm__pb2.ArmPingResponse.FromString,
                _registered_method=True)


class ArmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCartesianDelta(self, request, context):
        """Apply a delta Cartesian command to the arm end-effector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArmState(self, request, context):
        """Read the current arm state (Cartesian pose + joint positions)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Teleport the arm to a joint configuration (for episode resets)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCartesianDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCartesianDelta,
                    request_deserializer=arm__pb2.CartesianDelta.FromString,
                    response_serializer=arm__pb2.ArmCommandResponse.SerializeToString,
            ),
            'GetArmState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArmState,
                    request_deserializer=arm__pb2.GetArmStateRequest.FromString,
                    response_serializer=arm__pb2.ArmState.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=arm__pb2.ResetRequest.FromString,
                    response_serializer=arm__pb2.ArmCommandResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=arm__pb2.ArmPingRequest.FromString,
                    response_serializer=arm__pb2.ArmPingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openarm.ArmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openarm.ArmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCartesianDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.ArmService/SendCartesianDelta',
            arm__pb2.CartesianDelta.SerializeToString,
            arm__pb2.ArmCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArmState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.ArmService/GetArmState',
            arm__pb2.GetArmStateRequest.SerializeToString,
            arm__pb2.ArmState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.ArmService/Reset',
            arm__pb2.ResetRequest.SerializeToString,
            arm__pb2.ArmCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.ArmService/Ping',
            arm__pb2.ArmPingRequest.SerializeToString,
            arm__pb2.ArmPingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
