# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gripper_pb2 as gripper__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gripper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GripperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamState = channel.unary_stream(
                '/gripette.GripperService/StreamState',
                request_serializer=gripper__pb2.StreamRequest.SerializeToString,
                response_deserializer=gripper__pb2.GripperFrame.FromString,
                _registered_method=True)
        self.SendMotorCommand = channel.unary_unary(
                '/gripette.GripperService/SendMotorCommand',
                request_serializer=gripper__pb2.MotorCommand.SerializeToString,
                response_deserializer=gripper__pb2.MotorCommandResponse.FromString,
                _registered_method=True)
        self.ReadMotors = channel.unary_unary(
                '/gripette.GripperService/ReadMotors',
                request_serializer=gripper__pb2.ReadMotorsRequest.SerializeToString,
                response_deserializer=gripper__pb2.MotorState.FromString,
                _registered_method=True)
        self.SetTorque = channel.unary_unary(
                '/gripette.GripperService/SetTorque',
                request_serializer=gripper__pb2.TorqueCommand.SerializeToString,
                response_deserializer=gripper__pb2.TorqueResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/gripette.GripperService/Ping',
                request_serializer=gripper__pb2.PingRequest.SerializeToString,
                response_deserializer=gripper__pb2.PingResponse.FromString,
                _registered_method=True)


class GripperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamState(self, request, context):
        """Server-streaming: 10Hz camera frames + motor positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMotorCommand(self, request, context):
        """Unary: send goal positions to motors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMotors(self, request, context):
        """Unary: read motor positions (lightweight, no camera)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTorque(self, request, context):
        """Unary: enable/disable motor torque
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Unary: health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GripperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=gripper__pb2.StreamRequest.FromString,
                    response_serializer=gripper__pb2.GripperFrame.SerializeToString,
            ),
            'SendMotorCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMotorCommand,
                    request_deserializer=gripper__pb2.MotorCommand.FromString,
                    response_serializer=gripper__pb2.MotorCommandResponse.SerializeToString,
            ),
            'ReadMotors': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMotors,
                    request_deserializer=gripper__pb2.ReadMotorsRequest.FromString,
                    response_serializer=gripper__pb2.MotorState.SerializeToString,
            ),
            'SetTorque': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTorque,
                    request_deserializer=gripper__pb2.TorqueCommand.FromString,
                    response_serializer=gripper__pb2.TorqueResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=gripper__pb2.PingRequest.FromString,
                    response_serializer=gripper__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gripette.GripperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gripette.GripperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GripperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gripette.GripperService/StreamState',
            gripper__pb2.StreamRequest.SerializeToString,
            gripper__pb2.GripperFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMotorCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gripette.GripperService/SendMotorCommand',
            gripper__pb2.MotorCommand.SerializeToString,
            gripper__pb2.MotorCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMotors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gripette.GripperService/ReadMotors',
            gripper__pb2.ReadMotorsRequest.SerializeToString,
            gripper__pb2.MotorState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTorque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gripette.GripperService/SetTorque',
            gripper__pb2.TorqueCommand.SerializeToString,
            gripper__pb2.TorqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gripette.GripperService/Ping',
            gripper__pb2.PingRequest.SerializeToString,
            gripper__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
