# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gripper.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'gripper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgripper.proto\x12\x08gripette\"\x0f\n\rStreamRequest\"t\n\x0cGripperFrame\x12\x11\n\tjpeg_data\x18\x01 \x01(\x0c\x12)\n\x0bmotor_state\x18\x02 \x01(\x0b\x32\x14.gripette.MotorState\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x01\x12\x10\n\x08sequence\x18\x04 \x01(\x04\">\n\nMotorState\x12\x17\n\x0fmotor1_position\x18\x01 \x01(\x02\x12\x17\n\x0fmotor2_position\x18\x02 \x01(\x02\"8\n\x0cMotorCommand\x12\x13\n\x0bmotor1_goal\x18\x01 \x01(\x02\x12\x13\n\x0bmotor2_goal\x18\x02 \x01(\x02\"6\n\x14MotorCommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1f\n\rTorqueCommand\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\"0\n\x0eTorqueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x13\n\x11ReadMotorsRequest\"\r\n\x0bPingRequest\"6\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x02 \x01(\x01\x32\xd6\x02\n\x0eGripperService\x12@\n\x0bStreamState\x12\x17.gripette.StreamRequest\x1a\x16.gripette.GripperFrame0\x01\x12J\n\x10SendMotorCommand\x12\x16.gripette.MotorCommand\x1a\x1e.gripette.MotorCommandResponse\x12?\n\nReadMotors\x12\x1b.gripette.ReadMotorsRequest\x1a\x14.gripette.MotorState\x12>\n\tSetTorque\x12\x17.gripette.TorqueCommand\x1a\x18.gripette.TorqueResponse\x12\x35\n\x04Ping\x12\x15.gripette.PingRequest\x1a\x16.gripette.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gripper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=27
  _globals['_STREAMREQUEST']._serialized_end=42
  _globals['_GRIPPERFRAME']._serialized_start=44
  _globals['_GRIPPERFRAME']._serialized_end=160
  _globals['_MOTORSTATE']._serialized_start=162
  _globals['_MOTORSTATE']._serialized_end=224
  _globals['_MOTORCOMMAND']._serialized_start=226
  _globals['_MOTORCOMMAND']._serialized_end=282
  _globals['_MOTORCOMMANDRESPONSE']._serialized_start=284
  _globals['_MOTORCOMMANDRESPONSE']._serialized_end=338
  _globals['_TORQUECOMMAND']._serialized_start=340
  _globals['_TORQUECOMMAND']._serialized_end=371
  _globals['_TORQUERESPONSE']._serialized_start=373
  _globals['_TORQUERESPONSE']._serialized_end=421
  _globals['_READMOTORSREQUEST']._serialized_start=423
  _globals['_READMOTORSREQUEST']._serialized_end=442
  _globals['_PINGREQUEST']._serialized_start=444
  _globals['_PINGREQUEST']._serialized_end=457
  _globals['_PINGRESPONSE']._serialized_start=459
  _globals['_PINGRESPONSE']._serialized_end=513
  _globals['_GRIPPERSERVICE']._serialized_start=516
  _globals['_GRIPPERSERVICE']._serialized_end=858
# @@protoc_insertion_point(module_scope)
